# -*- coding: utf-8 -*-
"""OppBasic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_rvIMltGCvmx2WQxcLpa89d2ip9136wl
"""

lavadora1=washmachine("lg","x","123",5)

lavadora1.displayData()

class washmachine:
  def __init__(self,brandname,modelname,capacity,serialnumber):
   self.brandname = brandname
   self.modelname = modelname
   self.capacity = capacity
   self.serialnumber = serialnumber

  def displayData(self):
   print("\nBrandName : ",self.brandname)
   print("Modelname : ", self.modelname)
   print("Serial :", self.serialnumber)
   print("Capacity :", self.capacity)
  


#def __del__(self):
 # pass

#def accClothes(self):
  #pass

#def accDetergent(self):
 # pass
#def turnOf(self):
 # pass
 # def turnOff(self):
  #  pass  
#lavadora1=washmachine("lg","x","123",5)
#lavadora1.displayData()