# -*- coding: utf-8 -*-
"""Polimorfismo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZFZ0L9f_89Ih88qJ7aytt0OIAmaNht9
"""

from abc import ABC, abstractmethod

class Animal(ABC):
  def __init__(self,name):
    self.name=name
    
  @abstractmethod
  def talk(self):
    pass

class Dog(Animal):
  def talk(self):
    return f"Bow... Bow.."

class Duck(Animal):
  def talk(self):
    return f"Quaack...Quack..."



class Cat(Animal):
  def talk(self):
    return f"Meow Meow"

class Human(Animal):
  def talk(self):
    return f"I can talk more ..."

objelist=[Dog("Dog"),Cat("Cat"),Duck("Duck"),Human("Human")]

for obj in objelist:
  print("Name : %s" % obj.name)
  print("Talk : %s" % obj.talk())
  print("-"*30)