# -*- coding: utf-8 -*-
"""shape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1-2ILQKkEXIWTiuUE6zkhLVKvZtEW-L
"""

from abc import ABC, abstractmethod
class shape(ABC):
  @abstractmethod
  
  def area(self):
    pass

  def perimeter(self):
    pass

class Rectangle(shape):
      def __init__(self,lenght,width):
       self.__lenght =lenght
       self.__width = width

      def area(self):
        return  self.__lenght*self.__width

      def perimeter(self):
         return  2*(self.__lenght+self.__width)

r1=Rectangle(2,4)

print(r1.area())

print(r1.perimeter())